# Support the author by using the funding links below.
# This helps keep the backend online and the author motivated to maintain it.

buy_me_a_coffee: a.ws.m

# Your support means a lot to me and helps to keep open-source projects alive.
